version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clinical_backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend/db:/app/db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: clinical_frontend
    environment:
      - PORT=9006
      - BACKEND_URL=http://backend:5000
    ports:
      - "9006:9006"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_node_modules:
  frontend_node_modules:
